let skinMap = new Map()

skinMap.set(0, { name: "None" })
skinMap.set(2, { name: "Groundwater" })
skinMap.set(3, { name: "Candy Apple" })
skinMap.set(5, { name: "Forest DDPAT" })
skinMap.set(6, { name: "Arctic Camo" })
skinMap.set(8, { name: "Desert Storm" })
skinMap.set(9, { name: "Bengal Tiger" })
skinMap.set(10, { name: "Copperhead" })
skinMap.set(11, { name: "Skulls" })
skinMap.set(12, { name: "Crimson Web" })
skinMap.set(13, { name: "Blue Streak" })
skinMap.set(14, { name: "Red Laminate" })
skinMap.set(15, { name: "Gunsmoke" })
skinMap.set(16, { name: "Jungle Tiger" })
skinMap.set(17, { name: "Urban DDPAT" })
skinMap.set(20, { name: "Virus" })
skinMap.set(21, { name: "Granite Marbleized" })
skinMap.set(22, { name: "Contrast Spray" })
skinMap.set(25, { name: "Forest Leaves" })
skinMap.set(26, { name: "Lichen Dashed" })
skinMap.set(27, { name: "Bone Mask" })
skinMap.set(28, { name: "Anodized Navy" })
skinMap.set(30, { name: "Snake Camo" })
skinMap.set(32, { name: "Silver" })
skinMap.set(33, { name: "Hot Rod" })
skinMap.set(34, { name: "Metallic DDPAT" })
skinMap.set(36, { name: "Ossified" })
skinMap.set(37, { name: "Blaze" })
skinMap.set(38, { name: "Fade" })
skinMap.set(39, { name: "Bulldozer" })
skinMap.set(40, { name: "Night" })
skinMap.set(41, { name: "Copper" })
skinMap.set(42, { name: "Blue Steel" })
skinMap.set(43, { name: "Stained" })
skinMap.set(44, { name: "Case Hardened" })
skinMap.set(46, { name: "Contractor" })
skinMap.set(47, { name: "Colony" })
skinMap.set(48, { name: "Dragon Tattoo" })
skinMap.set(51, { name: "Lightning Strike" })
skinMap.set(59, { name: "Slaughter" })
skinMap.set(60, { name: "Dark Water" })
skinMap.set(61, { name: "Hypnotic" })
skinMap.set(62, { name: "Bloomstick" })
skinMap.set(67, { name: "Cold Blooded" })
skinMap.set(70, { name: "Carbon Fiber" })
skinMap.set(71, { name: "Scorpion" })
skinMap.set(72, { name: "Safari Mesh" })
skinMap.set(73, { name: "Wings" })
skinMap.set(74, { name: "Polar Camo" })
skinMap.set(75, { name: "Blizzard Marbleized" })
skinMap.set(76, { name: "Winter Forest" })
skinMap.set(77, { name: "Boreal Forest" })
skinMap.set(78, { name: "Forest Night" })
skinMap.set(83, { name: "Orange DDPAT" })
skinMap.set(84, { name: "Pink DDPAT" })
skinMap.set(90, { name: "Mudder" })
skinMap.set(92, { name: "Cyanospatter" })
skinMap.set(93, { name: "Caramel" })
skinMap.set(95, { name: "Grassland" })
skinMap.set(96, { name: "Blue Spruce" })
skinMap.set(98, { name: "Ultraviolet" })
skinMap.set(99, { name: "Sand Dune" })
skinMap.set(100, { name: "Storm" })
skinMap.set(101, { name: "Tornado" })
skinMap.set(102, { name: "Whiteout" })
skinMap.set(104, { name: "Grassland Leaves" })
skinMap.set(107, { name: "Polar Mesh" })
skinMap.set(110, { name: "Condemned" })
skinMap.set(111, { name: "Glacier Mesh" })
skinMap.set(116, { name: "Sand Mesh" })
skinMap.set(119, { name: "Sage Spray" })
skinMap.set(122, { name: "Jungle Spray" })
skinMap.set(124, { name: "Sand Spray" })
skinMap.set(125, { name: "X-Ray" })
skinMap.set(135, { name: "Urban Perforated" })
skinMap.set(136, { name: "Waves Perforated" })
skinMap.set(141, { name: "Orange Peel" })
skinMap.set(143, { name: "Urban Masked" })
skinMap.set(147, { name: "Jungle Dashed" })
skinMap.set(148, { name: "Sand Dashed" })
skinMap.set(149, { name: "Urban Dashed" })
skinMap.set(151, { name: "Jungle" })
skinMap.set(153, { name: "Demolition" })
skinMap.set(154, { name: "Afterimage" })
skinMap.set(155, { name: "Bullet Rain" })
skinMap.set(156, { name: "Death by Kitty" })
skinMap.set(157, { name: "Palm" })
skinMap.set(158, { name: "Walnut" })
skinMap.set(159, { name: "Brass" })
skinMap.set(162, { name: "Splash" })
skinMap.set(164, { name: "Modern Hunter" })
skinMap.set(165, { name: "Splash Jam" })
skinMap.set(166, { name: "Blaze Orange" })
skinMap.set(167, { name: "Radiation Hazard" })
skinMap.set(168, { name: "Nuclear Threat" })
skinMap.set(169, { name: "Fallout Warning" })
skinMap.set(170, { name: "Predator" })
skinMap.set(171, { name: "Irradiated Alert" })
skinMap.set(172, { name: "Black Laminate" })
skinMap.set(174, { name: "BOOM" })
skinMap.set(175, { name: "Scorched" })
skinMap.set(176, { name: "Faded Zebra" })
skinMap.set(177, { name: "Memento" })
skinMap.set(178, { name: "Doomkitty" })
skinMap.set(179, { name: "Nuclear Threat" })
skinMap.set(180, { name: "Fire Serpent" })
skinMap.set(181, { name: "Corticera" })
skinMap.set(182, { name: "Emerald Dragon" })
skinMap.set(183, { name: "Overgrowth" })
skinMap.set(184, { name: "Corticera" })
skinMap.set(185, { name: "Golden Koi" })
skinMap.set(186, { name: "Wave Spray" })
skinMap.set(187, { name: "Zirka" })
skinMap.set(188, { name: "Graven" })
skinMap.set(189, { name: "Bright Water" })
skinMap.set(190, { name: "Black Limba" })
skinMap.set(191, { name: "Tempest" })
skinMap.set(192, { name: "Shattered" })
skinMap.set(193, { name: "Bone Pile" })
skinMap.set(194, { name: "Spitfire" })
skinMap.set(195, { name: "Demeter" })
skinMap.set(196, { name: "Emerald" })
skinMap.set(197, { name: "Anodized Navy" })
skinMap.set(198, { name: "Hazard" })
skinMap.set(199, { name: "Dry Season" })
skinMap.set(200, { name: "Mayan Dreams" })
skinMap.set(201, { name: "Palm" })
skinMap.set(202, { name: "Jungle DDPAT" })
skinMap.set(203, { name: "Rust Coat" })
skinMap.set(204, { name: "Mosaico" })
skinMap.set(205, { name: "Jungle" })
skinMap.set(206, { name: "Tornado" })
skinMap.set(207, { name: "Facets" })
skinMap.set(208, { name: "Sand Dune" })
skinMap.set(209, { name: "Groundwater" })
skinMap.set(210, { name: "Anodized Gunmetal" })
skinMap.set(211, { name: "Ocean Foam" })
skinMap.set(212, { name: "Graphite" })
skinMap.set(213, { name: "Ocean Foam" })
skinMap.set(214, { name: "Graphite" })
skinMap.set(215, { name: "X-Ray" })
skinMap.set(216, { name: "Blue Titanium" })
skinMap.set(217, { name: "Blood Tiger" })
skinMap.set(218, { name: "Hexane" })
skinMap.set(219, { name: "Hive" })
skinMap.set(220, { name: "Hemoglobin" })
skinMap.set(221, { name: "Serum" })
skinMap.set(222, { name: "Blood in the Water" })
skinMap.set(223, { name: "Nightshade" })
skinMap.set(224, { name: "Water Sigil" })
skinMap.set(225, { name: "Ghost Camo" })
skinMap.set(226, { name: "Blue Laminate" })
skinMap.set(227, { name: "Electric Hive" })
skinMap.set(228, { name: "Blind Spot" })
skinMap.set(229, { name: "Azure Zebra" })
skinMap.set(230, { name: "Steel Disruption" })
skinMap.set(231, { name: "Cobalt Disruption" })
skinMap.set(232, { name: "Crimson Web" })
skinMap.set(233, { name: "Tropical Storm" })
skinMap.set(234, { name: "Ash Wood" })
skinMap.set(235, { name: "VariCamo" })
skinMap.set(236, { name: "Night Ops" })
skinMap.set(237, { name: "Urban Rubble" })
skinMap.set(238, { name: "VariCamo Blue" })
skinMap.set(240, { name: "CaliCamo" })
skinMap.set(241, { name: "Hunting Blind" })
skinMap.set(242, { name: "Army Mesh" })
skinMap.set(243, { name: "Gator Mesh" })
skinMap.set(244, { name: "Teardown" })
skinMap.set(245, { name: "Army Recon" })
skinMap.set(246, { name: "Amber Fade" })
skinMap.set(247, { name: "Damascus Steel" })
skinMap.set(248, { name: "Red Quartz" })
skinMap.set(249, { name: "Cobalt Quartz" })
skinMap.set(250, { name: "Full Stop" })
skinMap.set(251, { name: "Pit Viper" })
skinMap.set(252, { name: "Silver Quartz" })
skinMap.set(253, { name: "Acid Fade" })
skinMap.set(254, { name: "Nitro" })
skinMap.set(255, { name: "Asiimov" })
skinMap.set(256, { name: "The Kraken" })
skinMap.set(257, { name: "Guardian" })
skinMap.set(258, { name: "Mehndi" })
skinMap.set(259, { name: "Redline" })
skinMap.set(260, { name: "Pulse" })
skinMap.set(261, { name: "Marina" })
skinMap.set(262, { name: "Rose Iron" })
skinMap.set(263, { name: "Rising Skull" })
skinMap.set(264, { name: "Sandstorm" })
skinMap.set(265, { name: "Kami" })
skinMap.set(266, { name: "Magma" })
skinMap.set(267, { name: "Cobalt Halftone" })
skinMap.set(268, { name: "Tread Plate" })
skinMap.set(269, { name: "The Fuschia Is Now" })
skinMap.set(270, { name: "Victoria" })
skinMap.set(271, { name: "Undertow" })
skinMap.set(272, { name: "Titanium Bit" })
skinMap.set(273, { name: "Heirloom" })
skinMap.set(274, { name: "Copper Galaxy" })
skinMap.set(275, { name: "Red FragCam" })
skinMap.set(276, { name: "Panther" })
skinMap.set(277, { name: "Stainless" })
skinMap.set(278, { name: "Blue Fissure" })
skinMap.set(279, { name: "Asiimov" })
skinMap.set(280, { name: "Chameleon" })
skinMap.set(281, { name: "Corporal" })
skinMap.set(282, { name: "Redline" })
skinMap.set(283, { name: "Trigon" })
skinMap.set(284, { name: "Heat" })
skinMap.set(285, { name: "Terrain" })
skinMap.set(286, { name: "Antique" })
skinMap.set(287, { name: "Pulse" })
skinMap.set(288, { name: "Sergeant" })
skinMap.set(289, { name: "Sandstorm" })
skinMap.set(290, { name: "Guardian" })
skinMap.set(291, { name: "Heaven Guard" })
skinMap.set(293, { name: "Death Rattle" })
skinMap.set(294, { name: "Green Apple" })
skinMap.set(295, { name: "Franklin" })
skinMap.set(296, { name: "Meteorite" })
skinMap.set(297, { name: "Tuxedo" })
skinMap.set(298, { name: "Army Sheen" })
skinMap.set(299, { name: "Caged Steel" })
skinMap.set(300, { name: "Emerald Pinstripe" })
skinMap.set(301, { name: "Atomic Alloy" })
skinMap.set(302, { name: "Vulcan" })
skinMap.set(303, { name: "Isaac" })
skinMap.set(304, { name: "Slashed" })
skinMap.set(305, { name: "Torque" })
skinMap.set(306, { name: "Antique" })
skinMap.set(307, { name: "Retribution" })
skinMap.set(308, { name: "Kami" })
skinMap.set(309, { name: "Howl" })
skinMap.set(310, { name: "Curse" })
skinMap.set(311, { name: "Desert Warfare" })
skinMap.set(312, { name: "Cyrex" })
skinMap.set(313, { name: "Orion" })
skinMap.set(314, { name: "Heaven Guard" })
skinMap.set(315, { name: "Poison Dart" })
skinMap.set(316, { name: "Jaguar" })
skinMap.set(317, { name: "Bratatat" })
skinMap.set(318, { name: "Road Rash" })
skinMap.set(319, { name: "Detour" })
skinMap.set(320, { name: "Red Python" })
skinMap.set(321, { name: "Master Piece" })
skinMap.set(322, { name: "Nitro" })
skinMap.set(323, { name: "Rust Coat" })
skinMap.set(325, { name: "Chalice" })
skinMap.set(326, { name: "Knight" })
skinMap.set(327, { name: "Chainmail" })
skinMap.set(328, { name: "Hand Cannon" })
skinMap.set(329, { name: "Dark Age" })
skinMap.set(330, { name: "Briar" })
skinMap.set(332, { name: "Royal Blue" })
skinMap.set(333, { name: "Indigo" })
skinMap.set(334, { name: "Twist" })
skinMap.set(335, { name: "Module" })
skinMap.set(336, { name: "Desert-Strike" })
skinMap.set(337, { name: "Tatter" })
skinMap.set(338, { name: "Pulse" })
skinMap.set(339, { name: "Caiman" })
skinMap.set(340, { name: "Jet Set" })
skinMap.set(341, { name: "First Class" })
skinMap.set(342, { name: "Leather" })
skinMap.set(343, { name: "Commuter" })
skinMap.set(344, { name: "Dragon Lore" })
skinMap.set(345, { name: "First Class" })
skinMap.set(346, { name: "Coach Class" })
skinMap.set(347, { name: "Pilot" })
skinMap.set(348, { name: "Red Leather" })
skinMap.set(349, { name: "Osiris" })
skinMap.set(350, { name: "Tigris" })
skinMap.set(351, { name: "Conspiracy" })
skinMap.set(352, { name: "Fowl Play" })
skinMap.set(353, { name: "Water Elemental" })
skinMap.set(354, { name: "Urban Hazard" })
skinMap.set(355, { name: "Desert-Strike" })
skinMap.set(356, { name: "Koi" })
skinMap.set(357, { name: "Ivory" })
skinMap.set(358, { name: "Supernova" })
skinMap.set(359, { name: "Asiimov" })
skinMap.set(360, { name: "Cyrex" })
skinMap.set(361, { name: "Abyss" })
skinMap.set(362, { name: "Labyrinth" })
skinMap.set(363, { name: "Traveler" })
skinMap.set(364, { name: "Business Class" })
skinMap.set(365, { name: "Olive Plaid" })
skinMap.set(366, { name: "Green Plaid" })
skinMap.set(367, { name: "Reactor" })
skinMap.set(368, { name: "Setting Sun" })
skinMap.set(369, { name: "Nuclear Waste" })
skinMap.set(370, { name: "Bone Machine" })
skinMap.set(371, { name: "Styx" })
skinMap.set(372, { name: "Nuclear Garden" })
skinMap.set(373, { name: "Contamination" })
skinMap.set(374, { name: "Toxic" })
skinMap.set(375, { name: "Radiation Hazard" })
skinMap.set(376, { name: "Chemical Green" })
skinMap.set(377, { name: "Hot Shot" })
skinMap.set(378, { name: "Fallout Warning" })
skinMap.set(379, { name: "Cerberus" })
skinMap.set(380, { name: "Wasteland Rebel" })
skinMap.set(381, { name: "Grinder" })
skinMap.set(382, { name: "Murky" })
skinMap.set(383, { name: "Basilisk" })
skinMap.set(384, { name: "Griffin" })
skinMap.set(385, { name: "Firestarter" })
skinMap.set(386, { name: "Dart" })
skinMap.set(387, { name: "Urban Hazard" })
skinMap.set(388, { name: "Cartel" })
skinMap.set(389, { name: "Fire Elemental" })
skinMap.set(390, { name: "Highwayman" })
skinMap.set(391, { name: "Cardiac" })
skinMap.set(392, { name: "Delusion" })
skinMap.set(393, { name: "Tranquility" })
skinMap.set(394, { name: "Cartel" })
skinMap.set(395, { name: "Man-o'-war" })
skinMap.set(396, { name: "Urban Shock" })
skinMap.set(397, { name: "Naga" })
skinMap.set(398, { name: "Chatterbox" })
skinMap.set(399, { name: "Catacombs" })
skinMap.set(400, { name: "龍王 (Dragon King)" })
skinMap.set(401, { name: "System Lock" })
skinMap.set(402, { name: "Malachite" })
skinMap.set(403, { name: "Deadly Poison" })
skinMap.set(404, { name: "Muertos" })
skinMap.set(405, { name: "Serenity" })
skinMap.set(406, { name: "Grotto" })
skinMap.set(407, { name: "Quicksilver" })
skinMap.set(409, { name: "Tiger Tooth" })
skinMap.set(410, { name: "Damascus Steel" })
skinMap.set(411, { name: "Damascus Steel" })
skinMap.set(413, { name: "Marble Fade" })
skinMap.set(414, { name: "Rust Coat" })
skinMap.set(415, { name: "Doppler" })
skinMap.set(416, { name: "Doppler" })
skinMap.set(417, { name: "Doppler" })
skinMap.set(418, { name: "Doppler" })
skinMap.set(419, { name: "Doppler" })
skinMap.set(420, { name: "Doppler" })
skinMap.set(421, { name: "Doppler" })
skinMap.set(422, { name: "Elite Build" })
skinMap.set(423, { name: "Armor Core" })
skinMap.set(424, { name: "Worm God" })
skinMap.set(425, { name: "Bronze Deco" })
skinMap.set(426, { name: "Valence" })
skinMap.set(427, { name: "Monkey Business" })
skinMap.set(428, { name: "Eco" })
skinMap.set(429, { name: "Djinn" })
skinMap.set(430, { name: "Hyper Beast" })
skinMap.set(431, { name: "Heat" })
skinMap.set(432, { name: "Man-o'-war" })
skinMap.set(433, { name: "Neon Rider" })
skinMap.set(434, { name: "Origami" })
skinMap.set(435, { name: "Pole Position" })
skinMap.set(436, { name: "Grand Prix" })
skinMap.set(437, { name: "Twilight Galaxy" })
skinMap.set(438, { name: "Chronos" })
skinMap.set(439, { name: "Hades" })
skinMap.set(440, { name: "Icarus Fell" })
skinMap.set(441, { name: "Minotaur's Labyrinth" })
skinMap.set(442, { name: "Asterion" })
skinMap.set(443, { name: "Pathfinder" })
skinMap.set(444, { name: "Daedalus" })
skinMap.set(445, { name: "Hot Rod" })
skinMap.set(446, { name: "Medusa" })
skinMap.set(447, { name: "Duelist" })
skinMap.set(448, { name: "Pandora's Box" })
skinMap.set(449, { name: "Poseidon" })
skinMap.set(450, { name: "Moon in Libra" })
skinMap.set(451, { name: "Sun in Leo" })
skinMap.set(452, { name: "Shipping Forecast" })
skinMap.set(453, { name: "Emerald" })
skinMap.set(454, { name: "Para Green" })
skinMap.set(455, { name: "Akihabara Accept" })
skinMap.set(456, { name: "Hydroponic" })
skinMap.set(457, { name: "Bamboo Print" })
skinMap.set(458, { name: "Bamboo Shadow" })
skinMap.set(459, { name: "Bamboo Forest" })
skinMap.set(460, { name: "Aqua Terrace" })
skinMap.set(462, { name: "Counter Terrace" })
skinMap.set(463, { name: "Terrace" })
skinMap.set(464, { name: "Neon Kimono" })
skinMap.set(465, { name: "Orange Kimono" })
skinMap.set(466, { name: "Crimson Kimono" })
skinMap.set(467, { name: "Mint Kimono" })
skinMap.set(468, { name: "Midnight Storm" })
skinMap.set(469, { name: "Sunset Storm 壱" })
skinMap.set(470, { name: "Sunset Storm 弐" })
skinMap.set(471, { name: "Daybreak" })
skinMap.set(472, { name: "Impact Drill" })
skinMap.set(473, { name: "Seabird" })
skinMap.set(474, { name: "Aquamarine Revenge" })
skinMap.set(475, { name: "Hyper Beast" })
skinMap.set(476, { name: "Yellow Jacket" })
skinMap.set(477, { name: "Neural Net" })
skinMap.set(478, { name: "Rocket Pop" })
skinMap.set(479, { name: "Bunsen Burner" })
skinMap.set(480, { name: "Evil Daimyo" })
skinMap.set(481, { name: "Nemesis" })
skinMap.set(482, { name: "Ruby Poison Dart" })
skinMap.set(483, { name: "Loudmouth" })
skinMap.set(484, { name: "Ranger" })
skinMap.set(485, { name: "Handgun" })
skinMap.set(486, { name: "Elite Build" })
skinMap.set(487, { name: "Cyrex" })
skinMap.set(488, { name: "Riot" })
skinMap.set(489, { name: "Torque" })
skinMap.set(490, { name: "Frontside Misty" })
skinMap.set(491, { name: "Dualing Dragons" })
skinMap.set(492, { name: "Survivor Z" })
skinMap.set(493, { name: "Flux" })
skinMap.set(494, { name: "Stone Cold" })
skinMap.set(495, { name: "Wraiths" })
skinMap.set(496, { name: "Nebula Crusader" })
skinMap.set(497, { name: "Golden Coil" })
skinMap.set(498, { name: "Rangeen" })
skinMap.set(499, { name: "Cobalt Core" })
skinMap.set(500, { name: "Special Delivery" })
skinMap.set(501, { name: "Wingshot" })
skinMap.set(502, { name: "Green Marine" })
skinMap.set(503, { name: "Big Iron" })
skinMap.set(504, { name: "Kill Confirmed" })
skinMap.set(505, { name: "Scumbria" })
skinMap.set(506, { name: "Point Disarray" })
skinMap.set(507, { name: "Ricochet" })
skinMap.set(508, { name: "Fuel Rod" })
skinMap.set(509, { name: "Corinthian" })
skinMap.set(510, { name: "Retrobution" })
skinMap.set(511, { name: "The Executioner" })
skinMap.set(512, { name: "Royal Paladin" })
skinMap.set(514, { name: "Power Loader" })
skinMap.set(515, { name: "Imperial" })
skinMap.set(516, { name: "Shapewood" })
skinMap.set(517, { name: "Yorick" })
skinMap.set(518, { name: "Outbreak" })
skinMap.set(519, { name: "Tiger Moth" })
skinMap.set(520, { name: "Avalanche" })
skinMap.set(521, { name: "Teclu Burner" })
skinMap.set(522, { name: "Fade" })
skinMap.set(523, { name: "Amber Fade" })
skinMap.set(524, { name: "Fuel Injector" })
skinMap.set(525, { name: "Elite Build" })
skinMap.set(526, { name: "Photic Zone" })
skinMap.set(527, { name: "Kumicho Dragon" })
skinMap.set(528, { name: "Cartel" })
skinMap.set(529, { name: "Valence" })
skinMap.set(530, { name: "Triumvirate" })
skinMap.set(532, { name: "Royal Legion" })
skinMap.set(533, { name: "The Battlestar" })
skinMap.set(534, { name: "Lapis Gator" })
skinMap.set(535, { name: "Praetorian" })
skinMap.set(536, { name: "Impire" })
skinMap.set(537, { name: "Hyper Beast" })
skinMap.set(538, { name: "Necropos" })
skinMap.set(539, { name: "Jambiya" })
skinMap.set(540, { name: "Lead Conduit" })
skinMap.set(541, { name: "Fleet Flock" })
skinMap.set(542, { name: "Judgement of Anubis" })
skinMap.set(543, { name: "Red Astor" })
skinMap.set(544, { name: "Ventilators" })
skinMap.set(545, { name: "Orange Crash" })
skinMap.set(546, { name: "Firefight" })
skinMap.set(547, { name: "Spectre" })
skinMap.set(548, { name: "Chantico's Fire" })
skinMap.set(549, { name: "Bioleak" })
skinMap.set(550, { name: "Oceanic" })
skinMap.set(551, { name: "Asiimov" })
skinMap.set(552, { name: "Fubar" })
skinMap.set(553, { name: "Atlas" })
skinMap.set(554, { name: "Ghost Crusader" })
skinMap.set(555, { name: "Re-Entry" })
skinMap.set(556, { name: "Primal Saber" })
skinMap.set(557, { name: "Black Tie" })
skinMap.set(558, { name: "Lore" })
skinMap.set(559, { name: "Lore" })
skinMap.set(560, { name: "Lore" })
skinMap.set(561, { name: "Lore" })
skinMap.set(562, { name: "Lore" })
skinMap.set(563, { name: "Black Laminate" })
skinMap.set(564, { name: "Black Laminate" })
skinMap.set(565, { name: "Black Laminate" })
skinMap.set(566, { name: "Black Laminate" })
skinMap.set(567, { name: "Black Laminate" })
skinMap.set(568, { name: "Gamma Doppler" })
skinMap.set(569, { name: "Gamma Doppler" })
skinMap.set(570, { name: "Gamma Doppler" })
skinMap.set(571, { name: "Gamma Doppler" })
skinMap.set(572, { name: "Gamma Doppler" })
skinMap.set(573, { name: "Autotronic" })
skinMap.set(574, { name: "Autotronic" })
skinMap.set(575, { name: "Autotronic" })
skinMap.set(576, { name: "Autotronic" })
skinMap.set(577, { name: "Autotronic" })
skinMap.set(578, { name: "Bright Water" })
skinMap.set(579, { name: "Bright Water" })
skinMap.set(580, { name: "Freehand" })
skinMap.set(581, { name: "Freehand" })
skinMap.set(582, { name: "Freehand" })
skinMap.set(583, { name: "Aristocrat" })
skinMap.set(584, { name: "Phobos" })
skinMap.set(585, { name: "Violent Daimyo" })
skinMap.set(586, { name: "Wasteland Rebel" })
skinMap.set(587, { name: "Mecha Industries" })
skinMap.set(588, { name: "Desolate Space" })
skinMap.set(589, { name: "Carnivore" })
skinMap.set(590, { name: "Exo" })
skinMap.set(591, { name: "Imperial Dragon" })
skinMap.set(592, { name: "Iron Clad" })
skinMap.set(593, { name: "Chopper" })
skinMap.set(594, { name: "Harvester" })
skinMap.set(595, { name: "Reboot" })
skinMap.set(596, { name: "Limelight" })
skinMap.set(597, { name: "Bloodsport" })
skinMap.set(598, { name: "Aerial" })
skinMap.set(599, { name: "Ice Cap" })
skinMap.set(600, { name: "Neon Revolution" })
skinMap.set(601, { name: "Syd Mead" })
skinMap.set(602, { name: "Imprint" })
skinMap.set(603, { name: "Directive" })
skinMap.set(604, { name: "Roll Cage" })
skinMap.set(605, { name: "Scumbria" })
skinMap.set(606, { name: "Ventilator" })
skinMap.set(607, { name: "Weasel" })
skinMap.set(608, { name: "Petroglyph" })
skinMap.set(609, { name: "Airlock" })
skinMap.set(610, { name: "Dazzle" })
skinMap.set(611, { name: "Grim" })
skinMap.set(612, { name: "Powercore" })
skinMap.set(613, { name: "Triarch" })
skinMap.set(614, { name: "Fuel Injector" })
skinMap.set(615, { name: "Briefing" })
skinMap.set(616, { name: "Slipstream" })
skinMap.set(617, { name: "Doppler" })
skinMap.set(618, { name: "Doppler" })
skinMap.set(619, { name: "Doppler" })
skinMap.set(620, { name: "Ultraviolet" })
skinMap.set(621, { name: "Ultraviolet" })
skinMap.set(622, { name: "Polymer" })
skinMap.set(623, { name: "Ironwork" })
skinMap.set(624, { name: "Dragonfire" })
skinMap.set(625, { name: "Royal Consorts" })
skinMap.set(626, { name: "Mecha Industries" })
skinMap.set(627, { name: "Cirrus" })
skinMap.set(628, { name: "Stinger" })
skinMap.set(629, { name: "Black Sand" })
skinMap.set(630, { name: "Sand Scale" })
skinMap.set(631, { name: "Flashback" })
skinMap.set(632, { name: "Buzz Kill" })
skinMap.set(633, { name: "Sonar" })
skinMap.set(634, { name: "Gila" })
skinMap.set(635, { name: "Turf" })
skinMap.set(636, { name: "Shallow Grave" })
skinMap.set(637, { name: "Cyrex" })
skinMap.set(638, { name: "Wasteland Princess" })
skinMap.set(639, { name: "Bloodsport" })
skinMap.set(640, { name: "Fever Dream" })
skinMap.set(641, { name: "Jungle Slipstream" })
skinMap.set(642, { name: "Blueprint" })
skinMap.set(643, { name: "Xiangliu" })
skinMap.set(644, { name: "Decimator" })
skinMap.set(645, { name: "Oxide Blaze" })
skinMap.set(646, { name: "Capillary" })
skinMap.set(647, { name: "Crimson Tsunami" })
skinMap.set(648, { name: "Emerald Poison Dart" })
skinMap.set(649, { name: "Akoben" })
skinMap.set(650, { name: "Ripple" })
skinMap.set(651, { name: "Last Dive" })
skinMap.set(652, { name: "Scaffold" })
skinMap.set(653, { name: "Neo-Noir" })
skinMap.set(654, { name: "Seasons" })
skinMap.set(655, { name: "Zander" })
skinMap.set(656, { name: "Orbit Mk01" })
skinMap.set(657, { name: "Blueprint" })
skinMap.set(658, { name: "Cobra Strike" })
skinMap.set(659, { name: "Macabre" })
skinMap.set(660, { name: "Hyper Beast" })
skinMap.set(661, { name: "Sugar Rush" })
skinMap.set(662, { name: "Oni Taiji" })
skinMap.set(663, { name: "Briefing" })
skinMap.set(664, { name: "Hellfire" })
skinMap.set(665, { name: "Aloha" })
skinMap.set(666, { name: "Hard Water" })
skinMap.set(667, { name: "Woodsman" })
skinMap.set(668, { name: "Red Rock" })
skinMap.set(669, { name: "Death Grip" })
skinMap.set(670, { name: "Death's Head" })
skinMap.set(671, { name: "Cut Out" })
skinMap.set(672, { name: "Metal Flowers" })
skinMap.set(673, { name: "Morris" })
skinMap.set(674, { name: "Triqua" })
skinMap.set(675, { name: "The Empress" })
skinMap.set(676, { name: "High Roller" })
skinMap.set(677, { name: "Hunter" })
skinMap.set(678, { name: "See Ya Later" })
skinMap.set(679, { name: "Goo" })
skinMap.set(680, { name: "Off World" })
skinMap.set(681, { name: "Leaded Glass" })
skinMap.set(682, { name: "Oceanic" })
skinMap.set(683, { name: "Llama Cannon" })
skinMap.set(684, { name: "Cracked Opal" })
skinMap.set(685, { name: "Jungle Slipstream" })
skinMap.set(686, { name: "Phantom" })
skinMap.set(687, { name: "Tacticat" })
skinMap.set(688, { name: "Exposure" })
skinMap.set(689, { name: "Ziggy" })
skinMap.set(690, { name: "Stymphalian" })
skinMap.set(691, { name: "Mortis" })
skinMap.set(692, { name: "Night Riot" })
skinMap.set(693, { name: "Flame Test" })
skinMap.set(694, { name: "Moonrise" })
skinMap.set(695, { name: "Neo-Noir" })
skinMap.set(696, { name: "Bloodsport" })
skinMap.set(697, { name: "Black Sand" })
skinMap.set(698, { name: "Lionfish" })
skinMap.set(699, { name: "Wild Six" })
skinMap.set(700, { name: "Urban Hazard" })
skinMap.set(701, { name: "Grip" })
skinMap.set(702, { name: "Aloha" })
skinMap.set(703, { name: "SWAG-7" })
skinMap.set(704, { name: "Arctic Wolf" })
skinMap.set(705, { name: "Cortex" })
skinMap.set(706, { name: "Oxide Blaze" })
skinMap.set(707, { name: "Neon Rider" })
skinMap.set(708, { name: "Amber Slipstream" })
skinMap.set(709, { name: "Eco" })
skinMap.set(710, { name: "Shred" })
skinMap.set(711, { name: "Code Red" })
skinMap.set(712, { name: "High Seas" })
skinMap.set(713, { name: "Warhawk" })
skinMap.set(714, { name: "Nightmare" })
skinMap.set(715, { name: "Capillary" })
skinMap.set(716, { name: "Toy Soldier" })
skinMap.set(717, { name: "Traction" })
skinMap.set(718, { name: "PAW" })
skinMap.set(719, { name: "Powercore" })
skinMap.set(720, { name: "Devourer" })
skinMap.set(721, { name: "Survivalist" })
skinMap.set(722, { name: "Snek-9" })
skinMap.set(723, { name: "Eye of Athena" })
skinMap.set(724, { name: "Wild Lotus" })
skinMap.set(725, { name: "Day Lily" })
skinMap.set(726, { name: "Sunset Lily" })
skinMap.set(727, { name: "Midnight Lily" })
skinMap.set(728, { name: "Teal Blossom" })
skinMap.set(729, { name: "Crimson Blossom" })
skinMap.set(730, { name: "Dark Blossom" })
skinMap.set(731, { name: "Banana Leaf" })
skinMap.set(732, { name: "Synth Leaf" })
skinMap.set(733, { name: "Rust Leaf" })
skinMap.set(734, { name: "Wild Lily" })
skinMap.set(735, { name: "Night Stripe" })
skinMap.set(736, { name: "The Prince" })
skinMap.set(737, { name: "Cinquedea" })
skinMap.set(738, { name: "Orange Murano" })
skinMap.set(739, { name: "Violet Murano" })
skinMap.set(740, { name: "Navy Murano" })
skinMap.set(741, { name: "Dark Filigree" })
skinMap.set(742, { name: "Red Filigree" })
skinMap.set(743, { name: "Orange Filigree" })
skinMap.set(744, { name: "Baroque Red" })
skinMap.set(745, { name: "Baroque Purple" })
skinMap.set(746, { name: "Baroque Orange" })
skinMap.set(747, { name: "Twin Turbo" })
skinMap.set(748, { name: "Calf Skin" })
skinMap.set(749, { name: "Vino Primo" })
skinMap.set(750, { name: "Integrale" })
skinMap.set(751, { name: "Hand Brake" })
skinMap.set(752, { name: "Fade" })
skinMap.set(753, { name: "Dirt Drop" })
skinMap.set(754, { name: "Rust Coat" })
skinMap.set(755, { name: "Slide" })
skinMap.set(756, { name: "Gungnir" })
skinMap.set(757, { name: "Emerald Jörmungandr" })
skinMap.set(758, { name: "Flame Jörmungandr" })
skinMap.set(759, { name: "Astral Jörmungandr" })
skinMap.set(760, { name: "Frost Borre" })
skinMap.set(761, { name: "Copper Borre" })
skinMap.set(762, { name: "Red Stone" })
skinMap.set(763, { name: "Mjölnir" })
skinMap.set(775, { name: "Facility Sketch" })
skinMap.set(776, { name: "Facility Negative" })
skinMap.set(777, { name: "Facility Draft" })
skinMap.set(778, { name: "Facility Dark" })
skinMap.set(779, { name: "Random Access" })
skinMap.set(780, { name: "Mainframe" })
skinMap.set(781, { name: "Co-Processor" })
skinMap.set(782, { name: "Motherboard" })
skinMap.set(783, { name: "Bulkhead" })
skinMap.set(784, { name: "Coolant" })
skinMap.set(785, { name: "Mandrel" })
skinMap.set(786, { name: "Exchanger" })
skinMap.set(787, { name: "Core Breach" })
skinMap.set(788, { name: "Acheron" })
skinMap.set(789, { name: "Nuclear Garden" })
skinMap.set(790, { name: "Cold Fusion" })
skinMap.set(791, { name: "Remote Control" })
skinMap.set(792, { name: "Control Panel" })
skinMap.set(793, { name: "Converter" })
skinMap.set(794, { name: "Sweeper" })
skinMap.set(795, { name: "Safety Net" })
skinMap.set(796, { name: "Check Engine" })
skinMap.set(797, { name: "Brake Light" })
skinMap.set(798, { name: "Nitro" })
skinMap.set(799, { name: "High Beam" })
skinMap.set(800, { name: "Lab Rats" })
skinMap.set(801, { name: "Asiimov" })
skinMap.set(802, { name: "Momentum" })
skinMap.set(803, { name: "Neo-Noir" })
skinMap.set(804, { name: "Modest Threat" })
skinMap.set(805, { name: "Mecha Industries" })
skinMap.set(806, { name: "Scavenger" })
skinMap.set(807, { name: "Signal" })
skinMap.set(808, { name: "Oxide Blaze" })
skinMap.set(809, { name: "Wood Fired" })
skinMap.set(810, { name: "Phosphor" })
skinMap.set(811, { name: "Magnesium" })
skinMap.set(812, { name: "Pipe Down" })
skinMap.set(813, { name: "Nevermore" })
skinMap.set(814, { name: "Black Sand" })
skinMap.set(815, { name: "Danger Close" })
skinMap.set(816, { name: "Fubar" })
skinMap.set(817, { name: "Flashback" })
skinMap.set(835, { name: "Crypsis" })
skinMap.set(836, { name: "Uncharted" })
skinMap.set(837, { name: "Angry Mob" })
skinMap.set(838, { name: "Atheris" })
skinMap.set(839, { name: "Bamboozle" })
skinMap.set(840, { name: "Whitefish" })
skinMap.set(841, { name: "Light Rail" })
skinMap.set(842, { name: "Akoben" })
skinMap.set(843, { name: "Skull Crusher" })
skinMap.set(844, { name: "The Emperor" })
skinMap.set(845, { name: "Momentum" })
skinMap.set(846, { name: "Gauss" })
skinMap.set(847, { name: "Mischief" })
skinMap.set(848, { name: "Verdigris" })
skinMap.set(849, { name: "Off World" })
skinMap.set(850, { name: "Incinegator" })
skinMap.set(851, { name: "Moonrise" })
skinMap.set(852, { name: "Doppler" })
skinMap.set(853, { name: "Doppler" })
skinMap.set(854, { name: "Doppler" })
skinMap.set(855, { name: "Doppler" })
skinMap.set(856, { name: "Marble Fade" })
skinMap.set(857, { name: "Damascus Steel" })
skinMap.set(858, { name: "Damascus Steel" })
skinMap.set(859, { name: "Emerald Quartz" })
skinMap.set(860, { name: "Pyre" })
skinMap.set(861, { name: "Barricade" })
skinMap.set(862, { name: "Moss Quartz" })
skinMap.set(863, { name: "Night Borre" })
skinMap.set(864, { name: "Candy Apple" })
skinMap.set(865, { name: "Stone Mosaico" })
skinMap.set(866, { name: "Canal Spray" })
skinMap.set(867, { name: "Stained Glass" })
skinMap.set(868, { name: "Sea Calico" })
skinMap.set(869, { name: "Sundown" })
skinMap.set(870, { name: "Jungle Thicket" })
skinMap.set(871, { name: "Surfwood" })
skinMap.set(872, { name: "Bamboo Garden" })
skinMap.set(873, { name: "Seabird" })
skinMap.set(884, { name: "Embargo" })
skinMap.set(885, { name: "Rat Rod" })
skinMap.set(886, { name: "Arctic Wolf" })
skinMap.set(887, { name: "Containment Breach" })
skinMap.set(888, { name: "Acid Wash" })
skinMap.set(889, { name: "Decimator" })
skinMap.set(890, { name: "Plume" })
skinMap.set(891, { name: "Black Sand" })
skinMap.set(892, { name: "Memento" })
skinMap.set(893, { name: "Neon Ply" })
skinMap.set(894, { name: "Obsidian" })
skinMap.set(895, { name: "Balance" })
skinMap.set(896, { name: "Torn" })
skinMap.set(897, { name: "Colony IV" })
skinMap.set(898, { name: "Stalker" })
skinMap.set(899, { name: "Bloodshot" })
skinMap.set(900, { name: "Warbird" })
skinMap.set(902, { name: "Aztec" })
skinMap.set(903, { name: "Elite 1.6" })
skinMap.set(904, { name: "Decommissioned" })
skinMap.set(905, { name: "Flash Out" })
skinMap.set(906, { name: "Buddy" })
skinMap.set(907, { name: "Inferno" })
skinMap.set(908, { name: "Classic Crate" })
skinMap.set(909, { name: "Popdog" })
skinMap.set(910, { name: "Hydra" })
skinMap.set(911, { name: "Nostalgia" })
skinMap.set(913, { name: "Death by Puppy" })
skinMap.set(914, { name: "Assault" })
skinMap.set(915, { name: "Agent" })
skinMap.set(916, { name: "Plastique" })
skinMap.set(917, { name: "Wildfire" })
skinMap.set(918, { name: "Sacrifice" })
skinMap.set(919, { name: "Commemoration" })
skinMap.set(920, { name: "Boroque Sand" })
skinMap.set(941, { name: "Phantom Disruptor" })
skinMap.set(942, { name: "Tom Cat" })
skinMap.set(943, { name: "Capillary" })
skinMap.set(944, { name: "Distressed" })
skinMap.set(945, { name: "Blue Ply" })
skinMap.set(946, { name: "Player Two" })
skinMap.set(947, { name: "Disco Tech" })
skinMap.set(948, { name: "Justice" })
skinMap.set(949, { name: "Desert Strike" })
skinMap.set(950, { name: "Prototype" })
skinMap.set(951, { name: "Acid Etched" })
skinMap.set(952, { name: "Bone Forged" })
skinMap.set(953, { name: "Apocalypto" })
skinMap.set(954, { name: "Enforcer" })
skinMap.set(955, { name: "Darkwing" })
skinMap.set(956, { name: "Fever Dream" })
skinMap.set(957, { name: "Bullet Queen" })
skinMap.set(958, { name: "Ultralight" })
skinMap.set(959, { name: "Legion of Anubis" })
skinMap.set(960, { name: "Gnarled" })
skinMap.set(961, { name: "Monster Call" })
skinMap.set(962, { name: "Printstream" })
skinMap.set(963, { name: "Vogue" })
skinMap.set(964, { name: "Brother" })
skinMap.set(965, { name: "Allure" })
skinMap.set(966, { name: "Ol' Rusty" })
skinMap.set(967, { name: "Mainframe 001" })
skinMap.set(968, { name: "Cassette" })
skinMap.set(969, { name: "Freight" })
skinMap.set(970, { name: "Entombed" })
skinMap.set(971, { name: "Tooth Fairy" })
skinMap.set(972, { name: "Connexion" })
skinMap.set(973, { name: "Runic" })
skinMap.set(974, { name: "Kitbash" })
skinMap.set(975, { name: "Exoskeleton" })
skinMap.set(976, { name: "Vendetta" })
skinMap.set(977, { name: "Cocoa Rampage" })
skinMap.set(978, { name: "Dezastre" })
skinMap.set(979, { name: "Fairy Tale" })
skinMap.set(980, { name: "Digital Mesh" })
skinMap.set(981, { name: "Vandal" })
skinMap.set(982, { name: "Contaminant" })
skinMap.set(983, { name: "Deep Relief" })
skinMap.set(984, { name: "Printstream" })
skinMap.set(985, { name: "Cyber Security" })
skinMap.set(986, { name: "Condition Zero" })
skinMap.set(987, { name: "Clear Polymer" })
skinMap.set(988, { name: "Neo-Noir" })
skinMap.set(989, { name: "Parallax" })
skinMap.set(990, { name: "Gold Bismuth" })
skinMap.set(991, { name: "Monster Mashup" })
skinMap.set(992, { name: "The Bronze" })
skinMap.set(993, { name: "Global Offensive" })
skinMap.set(994, { name: "Charter" })
skinMap.set(995, { name: "Surveillance" })
skinMap.set(996, { name: "Threat Detected" })
skinMap.set(997, { name: "Dispatch" })
skinMap.set(998, { name: "Switch Board" })
skinMap.set(999, { name: "Prime Conspiracy" })
skinMap.set(1000, { name: "Run and Hide" })
skinMap.set(1001, { name: "Welcome to the Jungle" })
skinMap.set(1002, { name: "Berries And Cherries" })
skinMap.set(1003, { name: "Crime Scene" })
skinMap.set(1004, { name: "X-Ray" })
skinMap.set(1005, { name: "Heist" })
skinMap.set(1006, { name: "Night Heist" })
skinMap.set(1007, { name: "Vault Heist" })
skinMap.set(1008, { name: "Houndstooth" })
skinMap.set(1009, { name: "Hot Snakes" })
skinMap.set(1010, { name: "Phoenix Chalk" })
skinMap.set(1011, { name: "Phoenix Marker" })
skinMap.set(1012, { name: "Phoenix Stencil" })
skinMap.set(1013, { name: "Phoenix Blacklight" })
skinMap.set(1014, { name: "Clay Ambush" })
skinMap.set(1015, { name: "Tiger Pit" })
skinMap.set(1016, { name: "Franklin" })
skinMap.set(1017, { name: "Blue Phosphor" })
skinMap.set(1018, { name: "Panthera onca" })
skinMap.set(1019, { name: "Panther Camo" })
skinMap.set(1020, { name: "Ancient Earth" })
skinMap.set(1021, { name: "Ancient Lore" })
skinMap.set(1022, { name: "Lush Ruins" })
skinMap.set(1023, { name: "Tall Grass" })
skinMap.set(1024, { name: "Blast From the Past" })
skinMap.set(1025, { name: "Gold Brick" })
skinMap.set(1026, { name: "Fade" })
skinMap.set(1027, { name: "Target Acquired" })
skinMap.set(1028, { name: "Magna Carta" })
skinMap.set(1029, { name: "Silk Tiger" })
skinMap.set(1030, { name: "Bengal Tiger" })
skinMap.set(1031, { name: "Ancient Visions" })
skinMap.set(1032, { name: "Dusk Ruins" })
skinMap.set(1033, { name: "Carved Jade" })
skinMap.set(1034, { name: "Ancient Ritual" })
skinMap.set(10006, { name: "Charred" })
skinMap.set(10007, { name: "Snakebite" })
skinMap.set(10008, { name: "Bronzed" })
skinMap.set(10009, { name: "Leather" })
skinMap.set(10010, { name: "Spruce DDPAT" })
skinMap.set(10013, { name: "Lunar Weave" })
skinMap.set(10015, { name: "Convoy" })
skinMap.set(10016, { name: "Crimson Weave" })
skinMap.set(10018, { name: "Superconductor" })
skinMap.set(10019, { name: "Arid" })
skinMap.set(10021, { name: "Slaughter" })
skinMap.set(10024, { name: "Eclipse" })
skinMap.set(10026, { name: "Spearmint" })
skinMap.set(10027, { name: "Boom!" })
skinMap.set(10028, { name: "Cool Mint" })
skinMap.set(10030, { name: "Forest DDPAT" })
skinMap.set(10033, { name: "Crimson Kimono" })
skinMap.set(10034, { name: "Emerald Web" })
skinMap.set(10035, { name: "Foundation" })
skinMap.set(10036, { name: "Badlands" })
skinMap.set(10037, { name: "Pandora's Box" })
skinMap.set(10038, { name: "Hedge Maze" })
skinMap.set(10039, { name: "Guerrilla" })
skinMap.set(10040, { name: "Diamondback" })
skinMap.set(10041, { name: "King Snake" })
skinMap.set(10042, { name: "Imperial Plaid" })
skinMap.set(10043, { name: "Overtake" })
skinMap.set(10044, { name: "Racing Green" })
skinMap.set(10045, { name: "Amphibious" })
skinMap.set(10046, { name: "Bronze Morph" })
skinMap.set(10047, { name: "Omega" })
skinMap.set(10048, { name: "Vice" })
skinMap.set(10049, { name: "POW!" })
skinMap.set(10050, { name: "Turtle" })
skinMap.set(10051, { name: "Transport" })
skinMap.set(10052, { name: "Polygon" })
skinMap.set(10053, { name: "Cobalt Skulls" })
skinMap.set(10054, { name: "Overprint" })
skinMap.set(10055, { name: "Duct Tape" })
skinMap.set(10056, { name: "Arboreal" })
skinMap.set(10057, { name: "Emerald" })
skinMap.set(10058, { name: "Mangrove" })
skinMap.set(10059, { name: "Rattler" })
skinMap.set(10060, { name: "Case Hardened" })
skinMap.set(10061, { name: "Crimson Web" })
skinMap.set(10062, { name: "Buckshot" })
skinMap.set(10063, { name: "Fade" })
skinMap.set(10064, { name: "Mogul" })
skinMap.set(10065, { name: "Marble Fade" })
skinMap.set(10066, { name: "Lt. Commander" })
skinMap.set(10067, { name: "Tiger Strike" })
skinMap.set(10068, { name: "Field Agent" })
skinMap.set(10069, { name: "Rezan the Red" })
skinMap.set(10070, { name: "Snow Leopard" })
skinMap.set(10071, { name: "Queen Jaguar" })
skinMap.set(10072, { name: "Black Tie" })
skinMap.set(10073, { name: "Slingshot" })
skinMap.set(10074, { name: "Big Game" })
skinMap.set(10075, { name: "Scarlet Shamagh" })
skinMap.set(10076, { name: "Nocts" })
skinMap.set(10077, { name: "Finish Line" })
skinMap.set(10078, { name: "Smoke Out" })
skinMap.set(10079, { name: "Blood Pressure" })
skinMap.set(10080, { name: "3rd Commando Company" })
skinMap.set(10081, { name: "Desert Shamagh" })
skinMap.set(10082, { name: "Giraffe" })
skinMap.set(10083, { name: "Constrictor" })
skinMap.set(10084, { name: "CAUTION!" })
skinMap.set(10085, { name: "Jade" })
skinMap.set(10086, { name: "Yellow-banded" })
skinMap.set(10087, { name: "Needle Point" })
skinMap.set(10088, { name: "Unhinged" })

module.exports = skinMap;