let weaponArray =  new Map();

weaponArray.set(1,  { name: "Desert Eagle" });
weaponArray.set(2,  { name: "Dual Berettas" });
weaponArray.set(3,  { name: "Five-SeveN" });
weaponArray.set(4,  { name: "Glock-18" });
weaponArray.set(7,  { name: "AK-47" });
weaponArray.set(8,  { name: "AUG" });
weaponArray.set(9,  { name: "AWP", kit: 756 });
weaponArray.set(10,  { name: "FAMAS" });
weaponArray.set(11,  { name: "G3SG1" });
weaponArray.set(13,  { name: "Galil AR" });
weaponArray.set(14,  { name: "M249" });
weaponArray.set(16,  { name: "M4A4" });
weaponArray.set(17,  { name: "MAC-10" });
weaponArray.set(19,  { name: "P90" });
weaponArray.set(23,  { name: "MP5-SD" });
weaponArray.set(24,  { name: "UMP-45" });
weaponArray.set(25,  { name: "XM1014" });
weaponArray.set(26,  { name: "PP-Bizon" });
weaponArray.set(27,  { name: "MAG-7" });
weaponArray.set(28,  { name: "Negev" });
weaponArray.set(29,  { name: "Sawed-Off" });
weaponArray.set(30,  { name: "Tec-9" });
weaponArray.set(31,  { name: "Zeus x27" });
weaponArray.set(32,  { name: "P2000" });
weaponArray.set(33,  { name: "MP7" });
weaponArray.set(34,  { name: "MP9" });
weaponArray.set(35,  { name: "Nova" });
weaponArray.set(36,  { name: "P250" });
//weaponArray.set(37,  { name: "Ballistic Shield" });
weaponArray.set(38,  { name: "SCAR-20" });
weaponArray.set(39,  { name: "SG 553" });
weaponArray.set(40,  { name: "SSG 08" });
weaponArray.set(41,  { name: "Knife" });
weaponArray.set(42,  { name: "Knife" });
//weaponArray.set(43,  { name: "Flashbang" });
//weaponArray.set(44,  { name: "High Explosive Grenade" });
//weaponArray.set(45,  { name: "Smoke Grenade" });
//weaponArray.set(46,  { name: "Molotov" });
//weaponArray.set(47,  { name: "Decoy Grenade" });
//weaponArray.set(48,  { name: "Incendiary Grenade" });
//weaponArray.set(49,  { name: "C4 Explosive" });
//weaponArray.set(50,  { name: "Kevlar Vest" });
//weaponArray.set(51,  { name: "Kevlar + Helmet" });
//weaponArray.set(52,  { name: "Heavy Assault Suit" });
//weaponArray.set(54,  { name: "item_nvg" });
//weaponArray.set(55,  { name: "Defuse Kit" });
//weaponArray.set(56,  { name: "Rescue Kit" });
//weaponArray.set(57,  { name: "Medi-Shot" });
//weaponArray.set(58,  { name: "Music Kit" });
weaponArray.set(59,  { name: "Knife" });
weaponArray.set(60,  { name: "M4A1-S" });
weaponArray.set(61,  { name: "USP-S" });
weaponArray.set(63,  { name: "CZ75-Auto" });
weaponArray.set(64,  { name: "R8 Revolver" });
//weaponArray.set(68,  { name: "Tactical Awareness Grenade" });
//weaponArray.set(69,  { name: "Bare Hands" });
//weaponArray.set(70,  { name: "Breach Charge" });
//weaponArray.set(72,  { name: "Tablet" });
//weaponArray.set(75,  { name: "Axe" });
//weaponArray.set(76,  { name: "Hammer" });
//weaponArray.set(78,  { name: "Wrench" });
//weaponArray.set(80,  { name: "Spectral Shiv" });
//weaponArray.set(81,  { name: "Fire Bomb" });
//weaponArray.set(82,  { name: "Diversion Device" });
///weaponArray.set(83,  { name: "Frag Grenade" });
//weaponArray.set(84,  { name: "Snowball" });
//weaponArray.set(85,  { name: "Bump Mine" });
weaponArray.set(5027,  { name: "Bloodhound Gloves" });
weaponArray.set(5028,  { name: "Default T Gloves" });
weaponArray.set(5029,  { name: "Default CT Gloves" });
weaponArray.set(5030,  { name: "Sport Gloves" });
weaponArray.set(5031,  { name: "Driver Gloves" });
weaponArray.set(5032,  { name: "Hand Wraps" });
weaponArray.set(5033,  { name: "Moto Gloves" });
weaponArray.set(5034,  { name: "Specialist Gloves" });
weaponArray.set(5035,  { name: "Hydra Gloves" });
//weaponArray.set(5036,  { name: "Local T Agent" });
//weaponArray.set(5037,  { name: "Local CT Agent" });

module.exports = weaponArray;